flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint('main', __name__)


# by default router only accept GET
@main.route('/')
@main.route('/home')
def home():
    # posts = Post.query.order_by(Post.date_posted.desc()).all()
    # change to use pagination
    # read from GET params, set type to int
    # if value is not int, it will throw an error
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template('home.html', posts=posts) # **kwargs


@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm, DeletePostForm


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','ui positive message')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    form = DeletePostForm()
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!','ui positive message')
        return redirect(url_for('posts.post', post_id=post.id))
    if request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!','ui warning message')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, delete_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('register.html', form=form, title='Register')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') # get return none if key not exist, dictionary key will raise error
            return redirect(next_page) if next_page else redirect(url_for('main.home')) # python ternary operator
        flash('Unsuccessful login, please check email and password', 'ui negative message')
    return render_template('login.html', form=form, title='Login')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data: 
            if current_user.image_file and 'default.jpeg' not in current_user.image_file:
                delete_picture(current_user.image_file)
            current_user.image_file = save_picture(form.picture.data)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account info has been updated', 'ui positive message')
        return redirect('account')
    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pics/{ current_user.image_file }')
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=5, page=page)
    return render_template('user_posts.html', posts=posts, user=user) # **kwargs


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password.', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user: 
        flash('Invalid or expired token', 'ui warning message')
        return redirect(url_for('.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated!', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)
    

flaskblog/templates/components/_formhelpers.html
{# refer to WTForm documentation  #}
{% macro render_field(field) %}
  {{ field.label }}
  {{ field(**kwargs) | safe }}
  {% if field.errors %}
    {% for error in field.errors %}
      <div class="ui error message">{{ error }}</div>
    {% endfor %}
  {% endif %}
{% endmacro %}
{# not used in this project yet #}

flaskblog/templates/components/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
          <div class="{{ category }}">{{ message }}</div>
        {% endfor %}
    {% endif%}
{% endwith %}
{# pass along when calling a template #}
{% if error %}
  <div class="ui negative message">{{ error }}</div>
{% endif %}
{% if success %}
  <div class="ui positive messages">{{ success }}</div>
{% endif %}

flaskblog/templates/components/_navbar.html
  <div class="ui stackable blue inverted menu mb-2">
    <div class="header item">Flask Blog</div>
    <a href="{{ url_for('main.home') }}" class="item">home</a>
    <a href="{{ url_for('main.about') }}" class="item">about</a>
    <div class="right menu">
      {% if current_user.is_authenticated %}
        <a href="{{ url_for('posts.new_post') }}" class="item">New Post</a>
        <a href="{{ url_for('users.account') }}" class="item">{{ current_user.username }}</a>
        <a href="{{ url_for('users.logout') }}" class="item">Logout</a>
      {% else %}
        <a href="{{ url_for('users.login') }}" class="item">Login</a>
        <a href="{{ url_for('users.register') }}" class="item">Register</a>
      {% endif %}
    </div>
  </div>

flaskblog/templates/components/_sidebar.html
<div class="ui fluid vertical menu">
  <div class="item">
    <h3>Our Sidebar</h3>
    <p>You can put any information here</p>
  </div>
    <div class="link item">Latest Posts</div>
    <div class="link item">Announcements</div>
    <div class="link item">Calendars</div>
</div>