flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, validators, SubmitField


class PostForm(FlaskForm):
    title = StringField('Title', [validators.InputRequired()])
    content = TextAreaField('Content', [validators.InputRequired()])
    submit = SubmitField('Post')


class DeletePostForm(FlaskForm):
    pass

flaskblog/posts/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm, DeletePostForm


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','ui positive message')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    form = DeletePostForm()
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!','ui positive message')
        return redirect(url_for('posts.post', post_id=post.id))
    if request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!','ui warning message')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, delete_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('register.html', form=form, title='Register')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') # get return none if key not exist, dictionary key will raise error
            return redirect(next_page) if next_page else redirect(url_for('main.home')) # python ternary operator
        flash('Unsuccessful login, please check email and password', 'ui negative message')
    return render_template('login.html', form=form, title='Login')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data: 
            if current_user.image_file and 'default.jpeg' not in current_user.image_file:
                delete_picture(current_user.image_file)
            current_user.image_file = save_picture(form.picture.data)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account info has been updated', 'ui positive message')
        return redirect('account')
    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pics/{ current_user.image_file }')
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=5, page=page)
    return render_template('user_posts.html', posts=posts, user=user) # **kwargs


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password.', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated: return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user: 
        flash('Invalid or expired token', 'ui warning message')
        return redirect(url_for('.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated!', 'ui positive message')
        return redirect(url_for('.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)
    

flaskblog/templates/about.html
{% extends 'layout.html' %}

{% block body %}
  <h1>About Page</h1>
{% endblock body %}

flaskblog/templates/account.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <!-- <img src="userimage.jpg" alt="profile photo"> -->
    <!-- <div class="ui horizontal cards"> -->
      <div class="ui horizontal card">
        <div class="blurring dimmable image">
          <div class="ui dimmer">
            <div class="content">
              <div class="center">
                <div class="ui inverted button">Add Friend</div>
              </div>
            </div>
          </div>
          <img src="{{ image_file }}">
        </div>
        <div class="content">
          <a class="header">{{ current_user.username }}</a>
          <div class="meta">
            <span class="date">{{ current_user.email }}</span>
          </div>
        </div>
        {# <div class="extra content">
          <a>
            <i class="users icon"></i>
            2 Members
          </a>
        </div> #}
      </div>
    <!-- </div> -->
    
    <h3>Account Info</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" enctype="multipart/form-data" class="ui form {% if form.errors %}error{% endif %}">
      {{ form.csrf_token }}
      <div class="field">
        {{ form.username.label }}
        {{ form.username(class="text") }}
        {% if form.username.errors %}
        <div class="ui error message">
          {% for error in form.username.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="field">
        {{ form.email.label }}
        {{ form.email(class="text") }}
        {% if form.email.errors %}
        <div class="ui error message">
          {% for error in form.email.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="labeled action field">
        {{ form.picture.label(class="label") }}
        {{ form.picture(class="text") }}
        {% if form.picture.errors %}
        <div class="ui error message">
          <ul class="list">
          {% for error in form.picture.errors %}
              <li>{{ error }}</li>
          {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      {{ form.submit(class="ui button") }}
    </form>
  </div>

  <!-- <div class="ui segment">

    </div> -->
{% endblock body %}

flaskblog/templates/create_post.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <h3>{{ title }}</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" class="ui form {% if form.errors %}error{% endif %}" novalidate>
      {{ form.csrf_token }}
      <div class="field">
        {{ form.title.label }}
        {{ form.title(class="text") }}
        {% if form.title.errors %}
        <div class="ui error message">
          {% for error in form.title.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="field">
        {{ form.content.label }}
        {{ form.content(class="text") }}
        {% if form.content.errors %}
        <div class="ui error message">
          {% for error in form.content.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      {{ form.submit(class="ui button") }}
    </form>
  </div>
{% endblock body %}

flaskblog/templates/home.html
{% extends 'layout.html' %}

{% block body %}
  {% for post in posts.items %}
    <article class="ui segment">
      <h2 class="ui header"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <img class="ui avatar mini image" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <span class="ui small text">By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</span>
      <div class="ui divider"></div>
      <p>{{ post.content }}</p>
    </article>
  {% endfor %}
  <div class="ui pagination menu">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num%}
      <a class="active item" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
    <a class="item" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
    <a class="disabled item">...</a>
    {% endif %}
  {% endfor %}
  </div>
{% endblock body %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Flask Blog{% if title %} - {{ title }}{% endif %}</title>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.8/semantic.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  {% include 'components/_navbar.html' %}
  <div class="ui stackable two column grid container">
    <div class="sixteen wide mobile sixteen wide tablet eleven wide computer column">
      {% include 'components/_messages.html' %}
      {% block body %}{% endblock %}</div>
    <div class="sixteen wide mobile sixteen wide tablet five wide computer column">{% include 'components/_sidebar.html' %}</div>
  
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.8/semantic.min.js"></script>
  <script>
    $('.ui.basic.negative.button').click(function(){
      $('.ui.mini.modal').modal('show');
    });
  </script>
</body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <h3>Log In</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" class="ui form {% if form.errors %}error{% endif %}">
      {{ form.csrf_token }}
      <div class="{%if form.email.flags.required %}required{% endif %} field">
        {{ form.email.label }}
        {{ form.email(class="text") }}
        {% if form.email.errors %}
        <div class="ui error message">
          {% for error in form.email.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="{%if form.password.flags.required %}required{% endif %} field">
        {{ form.password.label }}
        {{ form.password(class="text") }}
      </div>
      <div class="inline field">
        <div class="ui toggle checkbox">
          {{ form.remember(class="hidden", tabindex=0) }}
          {{ form.remember.label }}
        </div>
      </div>
      {{ form.submit(class="ui button") }}
      <div class="mt"><a href="{{ url_for('users.reset_request') }}" class="ui small text">Forgot Password?</a></div>
    </form>
  </div>
  <div class="ui divider"></div>
  <p class="ui text">
    Need an Account ? <a href="{{ url_for('users.register') }}" class="ui text">Sign Up</a>
  </p>
{% endblock body %}

flaskblog/templates/post.html
{% extends 'layout.html' %}

{% block body %}
  <article class="ui segment">
    <h2 class="ui header">{{ post.title }}</h2>
    <img class="ui avatar mini image" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <span class="ui small text">By {{ post.author.username }} on {{ post.date_posted.strftime('%Y-%m-%d') }}</span>
    {% if post.author == current_user %}
    <div class="ui icon right floated small buttons">
      <a class="ui basic primary button" href="{{ url_for('posts.update_post', post_id=post.id) }}"><i class="icon edit outline"></i></a>
      <button class="ui basic negative button"><i class="icon trash alternate outline"></i></button>
    </div>
    {% endif %}
    <div class="ui divider"></div>
    <p>{{ post.content }}</p>
  </article>
  <div class="ui mini modal">
    <div class="ui icon header">
      <i class="trash alternate outline icon"></i>
      Delete Post ?
    </div>
    <div class="actions">
      <form style="display:inline;" action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
        {{ form.csrf_token }}
        <button class="ui green ok inverted button">
          <i class="checkmark icon"></i>
          Yes
        </button>
      </form>
      <div class="ui red cancel inverted button">
        <i class="remove icon"></i>
        No
      </div>
    </div>
  </div>
{% endblock body %}

flaskblog/templates/register.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <h3>Join Today</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" class="ui form {% if form.errors %}error{% endif %}">
      {{ form.csrf_token }}
      <div class="{%if form.username.flags.required %}required{% endif %} field">
        {{ form.username.label }}
        {{ form.username(class="text") }}
        {% if form.username.errors %}
        <div class="ui error message">
          {% for error in form.username.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="{%if form.email.flags.required %}required{% endif %} field">
        {{ form.email.label }}
        {{ form.email(class="text") }}
        {% if form.email.errors %}
        <div class="ui error message">
          {% for error in form.email.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="{%if form.password.flags.required %}required{% endif %} field">
        {{ form.password.label }}
        {{ form.password(class="text") }}
        {% if form.password.errors %}
        <div class="ui error message">
          {% for error in form.password.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="{%if form.confirm_password.flags.required %}required{% endif %} field">
        {{ form.confirm_password.label }}
        {{ form.confirm_password(class="text") }}
        {% if form.confirm_password.errors %}
        <div class="ui error message">
          {% for error in form.confirm_password.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      {#}
      {% if form.errors %}
          <div class="ui error message">
            <div class="header">Error</div>
            <ul class="list">
            {% for error in form.errors %}
              {% for err in form.errors[error] %}
                <li>{{ error }} - {{ err }}</li>
              {% endfor %}
            {% endfor %}
            </ul>
          </div>
      {% endif %} #}
      {{ form.submit(class="ui button") }}
    </form>
  </div>
  <div class="ui divider"></div>
  <p class="ui text">
    Already Have an Account ? <a href="{{ url_for('users.login') }}" class="ui text">Sign In</a>
  </p>
{% endblock body %}

flaskblog/templates/reset_request.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <h3>Reset Password</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" class="ui form {% if form.errors %}error{% endif %}">
      {{ form.csrf_token }}
      <div class="{%if form.email.flags.required %}required{% endif %} field">
        {{ form.email.label }}
        {{ form.email(class="text") }}
        {% if form.email.errors %}
        <div class="ui error message">
          {% for error in form.email.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      {{ form.submit(class="ui button") }}
    </form>
  </div>
{% endblock body %}

flaskblog/templates/reset_token.html
{% extends 'layout.html' %}

{% block body %}
  <div class="ui segment">
    <h3>Reset Password</h3>
    <div class="ui divider"></div>
    <form action="" method="POST" class="ui form {% if form.errors %}error{% endif %}">
      {{ form.csrf_token }}
      <div class="{%if form.password.flags.required %}required{% endif %} field">
        {{ form.password.label }}
        {{ form.password(class="text") }}
        {% if form.password.errors %}
        <div class="ui error message">
          {% for error in form.password.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="{%if form.confirm_password.flags.required %}required{% endif %} field">
        {{ form.confirm_password.label }}
        {{ form.confirm_password(class="text") }}
        {% if form.confirm_password.errors %}
        <div class="ui error message">
          {% for error in form.confirm_password.errors %}
              <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      {{ form.submit(class="ui button") }}
    </form>
  </div>
{% endblock body %}

flaskblog/templates/user_posts.html
{% extends 'layout.html' %}

{% block body %}
  <h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
  {% for post in posts.items %}
    <article class="ui segment">
      <h2 class="ui header"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <img class="ui avatar mini image" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <span class="ui small text">By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</span>
      <div class="ui divider"></div>
      <p>{{ post.content }}</p>
    </article>
  {% endfor %}
  <div class="ui pagination menu">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num%}
      <a class="active item" href="{{ url_for('users.user_posts',  username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
    <a class="item" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
    <a class="disabled item">...</a>
    {% endif %}
  {% endfor %}
  </div>
{% endblock body %}